[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
email_address = "0.2.9"
fancy-regex = "0.14.0"
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
